dotfiles_repo: git@github.com:aljets/dotfiles.git
dotfiles_repo_dest: ~/tools/dotfiles
dotfiles_files:
  - {file: '.vimrc', dest: ~/.vimrc}
  - {file: '.gitconfig', dest: ~/.gitconfig}
  - {file: '.tmux.conf', dest: ~/.tmux.conf}
  - {file: 'fish/config.fish', dest: ~/.config/fish/config.fish}  # requires fish to be run once before it works
  - {file: 'fish/functions', dest: ~/.config/fish/functions_from_dotfiles}
scripts_repo: git@github.com:aljets/dotfiles.git
scripts_repo_dest: ~/tools/dotfiles
scripts_repo_bin_directory: bin
tmux_plugin_manager_repo_dest: ~/tools/tmux-plugin-manager
brew_packages:
  - fish
  - the_silver_searcher
  - jq
  - git
  - vim
  - tldr
  - tmux
  - tfenv
  - node
apt_packages:
  - fish
  - silversearcher-ag
  - vim
  - npm
  - make
  - tldr
  - tmux
user_name: ajax
