dotfiles_repo: aljets/dotfiles
dotfiles_repo_dest: ~/tools/dotfiles
dotfiles_files:
  - {file: '.vimrc', dest: ~/.vimrc}
  - {file: '.tmux.conf', dest: ~/.tmux.conf}
  - {file: 'fish/config.fish', dest: ~/.config/fish/config.fish}
  - {file: 'fish/functions', dest: ~/.config/fish/functions_from_dotfiles}
scripts_repo: aljets/dotfiles
scripts_repo_dest: ~/tools/dotfiles
scripts_repo_bin_directory: bin
tmux_plugin_manager_repo_dest: ~/tools/tmux-plugin-manager
brew_packages:
  - fish
  - the_silver_searcher
  - jq
  - git
  - vim
  - tldr
  - reattach-to-user-namespace  # https://github.com/ChrisJohnsen/tmux-MacOSX-pasteboard
