---
- hosts: all
  tasks:
  - name: clone repo that is the source of the dotfiles
    # Fails (unfortunately) if local changes
    git:
      repo: "{{ dotfiles_repo }}"
      dest: "{{ dotfiles_repo_dest }}"
      accept_hostkey: yes
  - name: symlink dotfiles to location per config mapping
    # Fails (thankfully) if the dotfile exists and is a file
    file:
      src: "{{ dotfiles_repo_dest }}/{{ item.file }}"
      dest: "{{ item.dest }}"
      state: link
    with_items: "{{ dotfiles_files }}"
