---
- hosts: all
  tasks:
  - name: set up vim-plug
    get_url:
      url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
      dest: ~/.vim/autoload/plug.vim
  - name: upgrade plug
    shell: vim +PlugUpgrade +qall
  - name: update plugins
    shell: vim +PlugUpdate +qall
  - name: install plugins
    shell: vim +PlugInstall +qall
